### ISSUE TITLE
Self-contradicting documentation: Maven alternative?

### ISSUE THREAD

**Issue by obscurebyron** [Osiris-Team/1JPM#8]
Hello,

The documentation on this project appears to be self-contradicting:

> 1 Java Project Manager, is a Maven/Gradle alternative

> Note that 1JPM is now using Maven under the hood

I might be confused, but how can something be an alternative to something else, if it relies on that other thing?

**Comment by Osiris-Team** [comment]
The end-user/programmer is meant to use the JPM.java file instead of the pom.xml file, thus I consider it an alternative.

It would be more exact to call it something like an alternative frontend maybe, but I kept it like this for simplicity.
